import type { Locale } from '../../../i18n'

// Arabic display names for the built-in catalog items, keyed by the item's
// English `name`. The English name stays the source of truth (it's the stored
// node name and the search key); this map only localizes the *display*. Brand
// and proper-noun items (Tesla, IKEA, Herman Miller, …) are intentionally
// omitted so they render as-is.
const AR_NAMES: Record<string, string> = {
  Cactus: 'صبّار',
  'TV Stand': 'طاولة تلفاز',
  'Dining table': 'طاولة طعام',
  'Single Bed': 'سرير مفرد',
  'Livingroom Chair': 'كرسي صالة',
  'Small Plant': 'نبتة صغيرة',
  Column: 'عمود',
  Barbell: 'بار حديد',
  Toy: 'لعبة',
  'Barbell Stand': 'حامل بار حديد',
  Books: 'كتب',
  Stool: 'مقعد صغير',
  'Pool table': 'طاولة بلياردو',
  Bookshelf: 'رفّ كتب',
  'Coat Rack': 'علّاقة معاطف',
  'Car Toy': 'لعبة سيارة',
  'Bedside Table': 'طاولة جانبية',
  'Modular Cabinet': 'خزانة معيارية',
  Sofa: 'أريكة',
  Bunkbed: 'سرير طابقين',
  'My leather couch': 'أريكة جلدية',
  'Office Table': 'طاولة مكتب',
  'Dining Table': 'طاولة طعام',
  Guitar: 'غيتار',
  'Trash Bin': 'سلّة مهملات',
  'Recessed Light': 'إضاءة غائرة',
  Shelf: 'رفّ',
  'Table Lamp': 'مصباح طاولة',
  'Ceiling Lamp': 'مصباح سقف',
  Closet: 'خزانة ملابس',
  'Coffee Table': 'طاولة قهوة',
  'Dining Chair': 'كرسي طعام',
  Dresser: 'تسريحة',
  'Indoor Plant': 'نبتة داخلية',
  'Ironing Board': 'طاولة كي',
  'Double Bed': 'سرير مزدوج',
  'Floor Lamp': 'مصباح أرضي',
  Easel: 'حامل رسم',
  'Lounge Chair': 'كرسي استرخاء',
  'Office Chair': 'كرسي مكتب',
  Piano: 'بيانو',
  Picture: 'لوحة',
  'Rectangular Carpet': 'سجادة مستطيلة',
  'Rounded Mirror': 'مرآة دائرية',
  'Round Carpet': 'سجادة دائرية',
  Threadmill: 'جهاز مشي',
  'Standing Desk': 'مكتب واقف',
  Sprinkler: 'رشّاش',
  'Exit Sign': 'لافتة خروج',
  'Sewing Machine': 'ماكينة خياطة',
  Television: 'تلفاز',
  'Power Outlet': 'مقبس كهرباء',
  'AC block': 'وحدة تكييف',
  'Stereo Speaker': 'مكبّر صوت',
  Thermostat: 'منظّم حرارة',
  Toaster: 'محمّصة',
  Kettle: 'غلّاية',
  Hydrant: 'صنبور إطفاء',
  'Fire Detector': 'كاشف حريق',
  'Smoke Detector': 'كاشف دخان',
  'Coffee Machine': 'ماكينة قهوة',
  'Ceiling fan': 'مروحة سقف',
  Iron: 'مكواة',
  'Air Conditioning': 'مكيّف هواء',
  Computer: 'حاسوب',
  'Alarm Keypad': 'لوحة إنذار',
  'Ev-wall-charger': 'شاحن كهربائي جداري',
  'Electric Panel': 'لوحة كهرباء',
  'Bathroom Sink': 'مغسلة حمّام',
  'Angle Shower': 'دُش زاوية',
  'Toilet Paper': 'ورق تواليت',
  'Washing Machine': 'غسّالة',
  'Shower Rug': 'سجادة دُش',
  Bathtub: 'حوض استحمام',
  'Laundry Bag': 'كيس غسيل',
  'Squared Shower': 'دُش مربّع',
  'Drying Rack': 'حامل تجفيف',
  Toilet: 'مرحاض',
  Microwave: 'ميكروويف',
  'Cutting Board': 'لوح تقطيع',
  'Kitchen Utensils': 'أدوات مطبخ',
  'Kitchen Counter': 'طاولة مطبخ',
  Hood: 'شفّاط',
  'Kitchen Bar': 'بار مطبخ',
  'Kitchen Cabinet': 'خزانة مطبخ',
  Kitchen: 'مطبخ',
  'Frying Pan': 'مقلاة',
  Fruits: 'فواكه',
  Fridge: 'ثلّاجة',
  'Kitchen Shelf': 'رفّ مطبخ',
  'Wine Bottle': 'زجاجة نبيذ',
  Stove: 'موقد',
  Ball: 'كرة',
  Bush: 'شجيرة',
  'Basket Hoop': 'سلّة كرة',
  'Parking Spot': 'موقف سيارة',
  Palm: 'نخلة',
  Sunbed: 'كرسي شمس',
  Fir: 'شجرة صنوبر',
  Tree: 'شجرة',
  Skate: 'لوح تزلّج',
  'Outdoor Playhouse': 'بيت لعب خارجي',
  'Patio Umbrella': 'مظلّة فناء',
  Pillar: 'دعامة',
  Scooter: 'دراجة بخارية صغيرة',
  Dishwasher: 'غسّالة صحون',
  Fireplace: 'مدفأة',
}

// Localize a catalog item's display name. Falls back to the English name for
// any locale or item without a translation (e.g. brand names).
export function localizeCatalogName(name: string, locale: Locale): string {
  return locale === 'ar' ? (AR_NAMES[name] ?? name) : name
}
